stat_saving_enabled: false  # Save statistics and generate PDF report (true/false)
video_capture_enabled: false  # Enable video recording of the mission (true/false)


evaluation_plan:
  # Scenario 1: Intermediate map with 2 rounds, no special zones
  - map_name: MapMedium02
    nb_rounds: 1
    config_weight: 1
    zones_config: []